name: Run Test and Code Coverage

on:
  push:
    brances:
      - master
    pull_request:
      - master

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Depedencies
        run: yarn install

      - name: Run Test
        run: yarn test

      - name: Run Code Coverage
        run: yarn cov

      - name: Commit and Push Changes
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        run: |
          git config --local user.email "codecov.actions@github.com"
          git config --local user.name "Codecov"
          git add README.md
          git diff --cached --exit-code || git commit -m "Update codecov badge"
          git push origin master
